name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: edsonpimenta
          POSTGRESQL_PASSWORD: 123456
          POSTGRESQL_DATABASE: gympass_like

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_SECRET: supersecret
          DATABASE_URL: "postgresql://edsonpimenta:123456@localhost:5432/gympass_like?schema=public"
